# Лабораторная работа №3
## Работа с библиотекой NumPy

**Студент:** [Шихмагомедов Алим]  
**Группа:** [УСИС 24-4]  
**Дата выполнения:** [30.11.25]

---

### Цель работы
Освоение основных операций работы с массивами NumPy: создание, индексация, модификация, математические операции.

In [1]:
import numpy as np

# Проверяем версию NumPy
print(f"Версия NumPy: {np.__version__}")
print("=" * 60)

Версия NumPy: 2.0.2


In [2]:
# ========== ЗАДАЧА 1 ==========
print("ЗАДАЧА 1: Создать массив 10x10 со случайными значениями, найти минимум и максимум")
print("-" * 50)

# Создаем массив 10x10 со случайными значениями от 0 до 100
array_10x10 = np.random.rand(10, 10) * 100
print(f"Массив 10x10:\n{array_10x10}")
print(f"\nМинимальное значение: {array_10x10.min():.4f}")
print(f"Максимальное значение: {array_10x10.max():.4f}")
print(f"Среднее значение: {array_10x10.mean():.4f}")
print("=" * 60)

ЗАДАЧА 1: Создать массив 10x10 со случайными значениями, найти минимум и максимум
--------------------------------------------------
Массив 10x10:
[[89.32132936 10.41932252 51.56601975 19.19645933 99.76323318 68.17415939
  40.26671509 77.45884306 98.40257265 23.82004689]
 [78.39196402 80.35623164  3.91518893 10.00064528 13.95889367 46.35522188
  64.89785294 80.95112275 18.1874993  33.24326435]
 [ 4.28095717 40.10291111 93.64328077 90.46875805 95.00049149 16.56228014
  80.00559409 94.4082269  33.19164569 15.19886941]
 [61.08054496 81.75230032 50.42797797  4.94315999 68.66669932 62.42877787
  75.7697426  94.81885608 18.33418365 19.13077667]
 [ 3.20929195 48.82462561  0.62392332 14.61671023 20.38926194 88.01097175
  88.20721523 45.87065434 21.40143257 18.19624451]
 [98.43451672 70.72439769 12.05636848 73.53308775 67.36105288 54.62192947
   9.89332121 48.39017939 69.62494536 17.86187541]
 [10.2447845  16.50845601 90.50334592 77.29718261 96.26411811 87.10949376
  59.26219315 66.29159505 41.

In [3]:
# ========== ЗАДАЧА 2 ==========
print("\nЗАДАЧА 2: Создать 8x8 матрицу в шахматном порядке")
print("-" * 50)

# Способ 1: Используя срезы
chess_board = np.zeros((8, 8), dtype=int)
chess_board[1::2, ::2] = 1  # Нечетные строки, четные столбцы
chess_board[::2, 1::2] = 1  # Четные строки, нечетные столбцы

print("Шахматная доска 8x8:")
print(chess_board)
print("=" * 60)


ЗАДАЧА 2: Создать 8x8 матрицу в шахматном порядке
--------------------------------------------------
Шахматная доска 8x8:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [4]:
# ========== ЗАДАЧА 3 ==========
print("\nЗАДАЧА 3: Поменять знак у элементов, значения которых между 3 и 8")
print("-" * 50)

z = np.arange(11)
print(f"Исходный массив: {z}")

# Меняем знак у элементов между 3 и 8 (не включая границы)
mask = (z > 3) & (z < 8)
z[mask] = -z[mask]

print(f"Результат:       {z}")
print("=" * 60)


ЗАДАЧА 3: Поменять знак у элементов, значения которых между 3 и 8
--------------------------------------------------
Исходный массив: [ 0  1  2  3  4  5  6  7  8  9 10]
Результат:       [ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [5]:
# ========== ЗАДАЧА 4 ==========
print("\nЗАДАЧА 4: Найти среднее значение строки и вычесть его из каждого элемента")
print("-" * 50)

z = np.random.rand(5, 10)
print(f"Исходная матрица (5x10):\n{z}")

# Находим среднее по строкам (axis=1)
row_means = z.mean(axis=1, keepdims=True)  # keepdims сохраняет размерность
print(f"\nСредние значения строк: {row_means.flatten()}")

# Вычитаем среднее из каждой строки
z_normalized = z - row_means
print(f"\nМатрица после вычитания среднего:\n{z_normalized}")

# Проверка: среднее каждой строки должно быть ~0
print(f"\nПроверка (средние после нормализации): {z_normalized.mean(axis=1).round(10)}")
print("=" * 60)


ЗАДАЧА 4: Найти среднее значение строки и вычесть его из каждого элемента
--------------------------------------------------
Исходная матрица (5x10):
[[0.15198909 0.11358992 0.08640651 0.53929285 0.26289072 0.51446284
  0.68550073 0.94067105 0.76287049 0.14657886]
 [0.11058335 0.75359927 0.35007329 0.26394375 0.33021496 0.66143777
  0.7018551  0.00167245 0.13689517 0.17900892]
 [0.50586174 0.85107386 0.77544469 0.93860187 0.70647122 0.75627091
  0.79146631 0.78560794 0.14931228 0.58393442]
 [0.18994631 0.31008012 0.84030813 0.34487585 0.79748601 0.6165403
  0.32019841 0.09703021 0.23821238 0.22105743]
 [0.9717748  0.51813952 0.52763455 0.39211675 0.40101799 0.82204956
  0.34588926 0.47931143 0.37870163 0.84665339]]

Средние значения строк: [0.42042531 0.3489284  0.68440453 0.39757351 0.56832889]

Матрица после вычитания среднего:
[[-0.26843621 -0.30683538 -0.33401879  0.11886754 -0.15753459  0.09403753
   0.26507542  0.52024575  0.34244519 -0.27384645]
 [-0.23834505  0.40467087  0.001

In [6]:
# ========== ЗАДАЧА 5 ==========
print("\nЗАДАЧА 5: Поменять местами 1 и 2 строки матрицы")
print("-" * 50)

z = np.arange(25).reshape(5,5)
print(f"Исходная матрица 5x5:\n{z}")

# Меняем строки 1 и 2 (индексы 0 и 1)
z[[0, 1]] = z[[1, 0]]
print(f"\nМатрица после замены строк 1 и 2:\n{z}")
print("=" * 60)


ЗАДАЧА 5: Поменять местами 1 и 2 строки матрицы
--------------------------------------------------
Исходная матрица 5x5:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Матрица после замены строк 1 и 2:
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [7]:
# ========== ЗАДАЧА 6 ==========
print("\nЗАДАЧА 6: Преобразовать декартовы координаты в полярные")
print("-" * 50)

z = np.random.random((10,2)) * 10  # 10 точек, координаты от 0 до 10
print(f"Декартовы координаты (10 точек):\n{z}")

# Преобразование в полярные координаты
# r = sqrt(x² + y²), θ = arctan2(y, x)
x = z[:, 0]
y = z[:, 1]

r = np.sqrt(x**2 + y**2)  # Радиус
theta = np.arctan2(y, x)  # Угол в радианах

# Собираем результат
polar_coords = np.column_stack((r, theta))
print(f"\nПолярные координаты (радиус, угол в радианах):\n{polar_coords}")
print("=" * 60)


ЗАДАЧА 6: Преобразовать декартовы координаты в полярные
--------------------------------------------------
Декартовы координаты (10 точек):
[[6.72498297 3.89199835]
 [5.00232731 0.51826016]
 [4.43322037 9.45764888]
 [6.49001059 1.05566764]
 [6.61131531 7.25112551]
 [9.99305249 5.07019122]
 [1.06767107 6.06201459]
 [9.98054006 0.38301684]
 [5.26018672 6.46643854]
 [0.06222586 9.75789908]]

Полярные координаты (радиус, угол в радианах):
[[ 7.77000947  0.52463841]
 [ 5.02910252  0.10323549]
 [10.4451216   1.13246432]
 [ 6.57530772  0.16124816]
 [ 9.81266077  0.83151966]
 [11.20571002  0.4695275 ]
 [ 6.15531822  1.3964595 ]
 [ 9.98788675  0.03835754]
 [ 8.33572983  0.88790201]
 [ 9.75809748  1.56441944]]


In [8]:
# ========== ЗАДАЧА 7 ==========
print("\nЗАДАЧА 7: Заменить максимальный элемент массива на ноль")
print("-" * 50)

z = np.random.random(10)
print(f"Исходный массив: {z}")

# Находим индекс максимального элемента
max_index = np.argmax(z)
print(f"Максимальный элемент: z[{max_index}] = {z[max_index]:.4f}")

# Заменяем максимальный элемент на 0
z[max_index] = 0
print(f"Результат:         {z}")
print("=" * 60)


ЗАДАЧА 7: Заменить максимальный элемент массива на ноль
--------------------------------------------------
Исходный массив: [0.60211303 0.25412255 0.62466634 0.29602622 0.78591296 0.54828616
 0.01772335 0.76841834 0.26699066 0.02096961]
Максимальный элемент: z[4] = 0.7859
Результат:         [0.60211303 0.25412255 0.62466634 0.29602622 0.         0.54828616
 0.01772335 0.76841834 0.26699066 0.02096961]


In [9]:
# ========== ЗАДАЧА 8 ==========
print("\nЗАДАЧА 8: Добавить 1 к элементам с заданными индексами (только 1 раз)")
print("-" * 50)

z = np.ones(10)
i = np.random.randint(0, len(z), 20)  # 20 случайных индексов
print(f"Исходный массив: {z}")
print(f"Индексы для добавления (могут повторяться): {i}")

# Находим уникальные индексы
unique_indices = np.unique(i)
print(f"Уникальные индексы: {unique_indices}")

# Добавляем 1 только к уникальным индексам
z[unique_indices] += 1
print(f"Результат:         {z}")
print("=" * 60)


ЗАДАЧА 8: Добавить 1 к элементам с заданными индексами (только 1 раз)
--------------------------------------------------
Исходный массив: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Индексы для добавления (могут повторяться): [4 6 6 4 9 3 6 3 0 4 3 5 8 5 5 3 5 6 4 2]
Уникальные индексы: [0 2 3 4 5 6 8 9]
Результат:         [2. 1. 2. 2. 2. 2. 2. 1. 2. 2.]


In [10]:
# ========== ЗАДАЧА 9 ==========
print("\nЗАДАЧА 9: Вставить три нуля между каждым элементом вектора")
print("-" * 50)

z = np.array([1, 2, 3, 4, 5])
print(f"Исходный вектор: {z}")

# Создаем новый массив с нулями
# Длина нового массива: 5 элементов + (5-1) * 3 нулей = 17
result = np.zeros(len(z) + (len(z) - 1) * 3, dtype=z.dtype)

# Вставляем исходные элементы на каждую 4-ю позицию
result[::4] = z

print(f"Результат:        {result}")
print("=" * 60)


ЗАДАЧА 9: Вставить три нуля между каждым элементом вектора
--------------------------------------------------
Исходный вектор: [1 2 3 4 5]
Результат:        [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


In [11]:
# ========== ЗАДАЧА 10 ==========
print("\nЗАДАЧА 10: Найти ближайшее к заданному значению число в массиве")
print("-" * 50)

z = np.arange(100)  # Упорядоченный массив от 0 до 99
v = np.random.uniform(0, 100)  # Случайное число от 0 до 100
print(f"Массив: от 0 до 99")
print(f"Искомое значение: v = {v:.4f}")

# Находим индекс ближайшего элемента
# Способ 1: используя argmin с абсолютной разницей
idx = np.argmin(np.abs(z - v))
nearest_value = z[idx]

print(f"Ближайшее значение: z[{idx}] = {nearest_value}")
print(f"Разница: |{v:.4f} - {nearest_value}| = {abs(v - nearest_value):.4f}")
print("=" * 60)


ЗАДАЧА 10: Найти ближайшее к заданному значению число в массиве
--------------------------------------------------
Массив: от 0 до 99
Искомое значение: v = 19.8648
Ближайшее значение: z[20] = 20
Разница: |19.8648 - 20| = 0.1352


## Выводы
1. Освоены основные операции работы с массивами NumPy
2. Решены 10 задач на создание, модификацию и преобразование массивов
3. Использованы ключевые функции NumPy:
   - Создание массивов: `np.random.rand()`, `np.arange()`, `np.zeros()`
   - Математические операции: `mean()`, `max()`, `min()`, `sqrt()`, `arctan2()`
   - Индексация: булева индексация, fancy indexing, срезы
   - Поиск: `argmin()`, `argmax()`, `np.unique()`

**Основные сложности:** Правильное использование осей (axis) в многомерных массивах.